version: '3.8'

services:
  frontend:
    image: saisamarth21/lms-frontend:latest
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "5173:5173"
    networks:
      - lms-network
    depends_on:
      - backend

  backend:
    image: saisamarth21/lms-backend:latest
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://lms_user:lms_password@mongodb:27017/lms?authSource=admin
      - PORT=4000
      - NODE_ENV=production
    networks:
      - lms-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lms_user
      - MONGO_INITDB_ROOT_PASSWORD=lms_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - lms-network
    restart: always

networks:
  lms-network:
    driver: bridge

volumes:
  mongodb_data: