version: '3.8'

services:
  frontend:
    image: your-dockerhub-username/lms-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:4000
    ports:
      - "5173:5173"
    networks:
      - lms-network
    depends_on:
      - backend

  backend:
    image: your-dockerhub-username/lms-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://lms_user:lms_password@mongodb:27017/lms?authSource=admin
      - PORT=4000
    networks:
      - lms-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lms_user
      - MONGO_INITDB_ROOT_PASSWORD=lms_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongodb_data: