version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - lms-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_CONNECTION_URL=mongodb://mongodb:27017/lms
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongodb
    networks:
      - lms-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongodb_data: 