version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:4000       # <-- use the *service name* on the same network
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - lms-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/lms
      - PORT=4000
    depends_on:
      - mongodb
    networks:
      - lms-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongodb_data: 